### PR TITLE
Keystone notification logging

### PR DESCRIPTION
**Pull request by kamidzi**
Adds logging of keystone event notifications; by default, to local file.

### CODE REVIEW

**Comment by erhudy** [comment]
It looks like Keystone log events are being duplicated to both `/var/log/keystone/keystone.log` and `/var/log/apache2/keystone.log`. We can safely turn off the error log in Apache's configuration for the WSGI Keystone virtual host since that's all getting logged to `/var/log/keystone/keystone.log` now (maybe the access log too, though it might not hurt to keep the Apache access logs).

**Comment by kamidzi** [comment]
For sure; removed ErrorLog from template.

**Comment by erhudy** [comment]
Hit another problem after a fresh build, namely that `/var/log/keystone/keystone.log` gets created as owned by `root:root` somehow and Keystone won't start up. Looking into why it gets created with these permissions:
```
2015-07-30 10:02:40.754375 Traceback (most recent call last):
2015-07-30 10:02:40.754393   File "/var/www/cgi-bin/keystone/main", line 25, in <module>
2015-07-30 10:02:40.754450     application = wsgi_server.initialize_application(name)
2015-07-30 10:02:40.754461   File "/usr/lib/python2.7/dist-packages/keystone/server/wsgi.py", line 38, in initialize_application
2015-07-30 10:02:40.754498     common.configure()
2015-07-30 10:02:40.754507   File "/usr/lib/python2.7/dist-packages/keystone/server/common.py", line 36, in configure
2015-07-30 10:02:40.754545     config.setup_logging()
2015-07-30 10:02:40.754554   File "/usr/lib/python2.7/dist-packages/keystone/config.py", line 56, in setup_logging
2015-07-30 10:02:40.754594     log.setup(CONF, 'keystone')
2015-07-30 10:02:40.754603   File "/usr/lib/python2.7/dist-packages/oslo_log/log.py", line 211, in setup
2015-07-30 10:02:40.754695     _setup_logging_from_conf(conf, product_name, version)
2015-07-30 10:02:40.754705   File "/usr/lib/python2.7/dist-packages/oslo_log/log.py", line 263, in _setup_logging_from_conf
2015-07-30 10:02:40.754719     filelog = logging.handlers.WatchedFileHandler(logpath)
2015-07-30 10:02:40.754725   File "/usr/lib/python2.7/logging/handlers.py", line 391, in __init__
2015-07-30 10:02:40.754968     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
2015-07-30 10:02:40.754980   File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
2015-07-30 10:02:40.755288     StreamHandler.__init__(self, self._open())
2015-07-30 10:02:40.755299   File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
2015-07-30 10:02:40.755313     stream = open(self.baseFilename, self.mode)
2015-07-30 10:02:40.755330 IOError: [Errno 13] Permission denied: '/var/log/keystone/keystone.log'
```

**Comment by erhudy** [comment]
I think it gets created as `root:root` because the standalone Keystone service automatically starts as root before Chef can stop and disable it. I will add a resource in to ensure that the logfile is chowned appropriately and to restart Apache if necessary.

**Comment by erhudy** [comment]
This seems fine to me now, crushing and merging.

**Pull request merged**
