### PR TITLE
Allow tenants to modify instance metadata

### PR DESCRIPTION
**Pull request by semenovroman**
Resolves https://github.com/bloomberg/bcpc/issues/753

### CODE REVIEW

**Comment by erhudy** [comment]
What's the right way to test this? Without this patch applied, I'm able to launch instances as a regular non-admin user in a new tenancy and pass in metadata via `nova boot --meta`, as well as user data via `--user-data`.

**Comment by jerenkrantz** [comment]
I think that Fog changes the metadata *after* instance creation.

**Comment by erhudy** [comment]
I see. `nova meta` does get angry in expected ways, then:
```
$ nova meta test set meep=bleep
ERROR (Forbidden): Policy doesn't allow compute:update_instance_metadata to be performed. (HTTP 403)
$ nova meta test delete meep=bleep
ERROR (Forbidden): Policy doesn't allow compute:get_instance_metadata to be performed. (HTTP 403)
```

**Comment by semenovroman** [comment]
@erhudy  After this PR is applied you should be able to set\modify existing instance metadata without any errors. `nova meta test set meep=bleep` is expected to work fine with this patch.

**Comment by erhudy** [comment]
After patch works as expected:
```
$ nova meta test set meep=bleep
$ nova meta test delete meep=bleep
$ nova meta test delete moop=bloop
ERROR (NotFound): Metadata item was not found (HTTP 404)
```

**Pull request merged**
